import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/tailwind'

const sans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
  fallback: ['Open Sans']
})

export const metadata: Metadata = {
  title: 'You can do this!',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ cn(
        sans.variable,
        "font-sans",
        "bg-black",
        "text-white/70",
      ) }>{ children }</body>
    </html>
  )
}
