import type { Metadata } from 'next'
import { Inter, Open_Sans, Outfit } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/tailwind'

const sans = Inter({
  subsets: ['latin'],
  variable: '--font-open-sans',
})

const logo = Outfit({
  subsets: ['latin'],
  variable: '--font-logo',
})

export const metadata: Metadata = {
  title: 'You can do this!',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ cn(
        sans.variable,
        logo.variable,
        "font-sans",
        "bg-black",
        "text-indigo-100/90",
        "bg-gradient-to-b from-indigo-200/10 to-indigo-500/20",
        "selection:bg-green-800"
      ) }>
        { children }
      </body>
    </html>
  )
}
